[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
typed_floats = "1.0.x"

[dependencies.uuid]
version = "1.10.0"
features = [
    "v4",                # Lets you generate random UUIDs
]
